apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
    component: kafka-connector
  name: kafka-connector
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      component: kafka-connector
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: kafka
        component: kafka-connector
    spec:
      imagePullSecrets:
      - name: aliyunhangzhou
      containers:
      - name: kafka
        image: registry.cn-hangzhou.aliyuncs.com/byzanteam/kafka-connector:v0.1
        env:
          - name: gateway_url
            value: "http://gateway.openfaas.svc.cluster.local:8080"
          - name: broker_host
            value : "kafka.openfaas.svc.cluster.local:9092"
          - name: topics
            value: "faas-topics.*"
          - name: print_response
            value: "true"
          - name: print_response_body
            value: "true"
          - name: basic_auth
            value: "true"
          - name: secret_mount_path
            value: "/var/secrets/"
          - name: topic_delimiter
            value: ","
          - name: asynchronous_invocation
            value: "false"
        volumeMounts:
            - name: auth
              readOnly: true
              mountPath: "/var/secrets/"
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
