version: '3.3'
services:
    zookeeper:
        image: 'bitnami/zookeeper:3'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
            
    kafka:
        image: 'bitnami/kafka:2'
        ports:
            - '32762:9092'
            - '29092:29092'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        depends_on:
            - zookeeper
 
#version: '2'
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka1:
#    image: wurstmeister/kafka
#    ports:
#    - "32762:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 47.92.77.253
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#  kafka2:
#    image: wurstmeister/kafka
#    ports:
#    - "32761:9092"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_HOST_NAME: 47.92.77.253
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#  kafka3:
#    image: wurstmeister/kafka
#    ports:
#    - "32760:9092"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_HOST_NAME: 47.92.77.253
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#
